1. Create a NumPy array 'arr' of integers from to 5 and print its data type. 

In [1]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)


int64


2. Given a NumPy array 'arr', check if its data type is float64. 

arr = np.array([1.5, 2.6, 3.7])

In [2]:
import numpy as np

arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype == np.float64)


True


3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [3]:
import numpy as np

arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print(arr)


[1.+2.j 3.+4.j 5.+6.j]


 4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4])
arr = arr.astype(np.float32)
print(arr)


[1. 2. 3. 4.]


 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [5]:
import numpy as np

arr = np.array([1.5, 2.5, 3.5], dtype=np.float64)
arr = arr.astype(np.float32)
print(arr)


[1.5 2.5 3.5]


 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data 
type 

In [74]:
import numpy as np

def array_attributes(arr):
    """
    Returns the shape, size, and data type of a NumPy array.
    
    Parameters:
        arr (numpy.ndarray): Input NumPy array.
    
    Returns:
        tuple: (shape, size, dtype)
    """
    return arr.shape, arr.size, arr.dtype

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_attributes(arr))


((2, 3), 6, dtype('int64'))


7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [75]:
import numpy as np

def array_dimension(arr):
    """
    Returns the dimensionality of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        int: The number of dimensions of the array.
    """
    return arr.ndim

# Example usage
arr = np.array([[[1, 2, 3], [4, 5, 6]]])  # 3D array
print(array_dimension(arr))  # Output: 3


3


 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total 
size in bytes

In [76]:
import numpy as np

def item_size_info(arr):
    """
    Returns the item size and total size in bytes of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: (item size in bytes, total size in bytes)
    """
    return arr.itemsize, arr.nbytes

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print(item_size_info(arr))  # Output: (4, 24) for int32 type


(4, 24)


 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array

In [77]:
import numpy as np

def array_strides(arr):
    """
    Returns the strides of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: Strides of the array.
    """
    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print(array_strides(arr))  # Output: (12, 4) for int32 type


(12, 4)


 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape 
and strides of the array

In [78]:
import numpy as np

def shape_stride_relationship(arr):
    """
    Returns the shape and strides of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: (shape, strides)
    """
    return arr.shape, arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
print(shape_stride_relationship(arr))  # Output: ((2, 3), (12, 4)) for int32 type



((2, 3), (12, 4))


11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of 
zeros with `n` elements

In [79]:
import numpy as np

def create_zeros_array(n):
    """
    Creates a NumPy array of zeros with n elements.

    Parameters:
        n (int): Number of elements in the array.

    Returns:
        numpy.ndarray: Array of zeros with n elements.
    """
    return np.zeros(n)

# Example usage
arr = create_zeros_array(5)
print(arr)  # Output: [0. 0. 0. 0. 0.]



[0. 0. 0. 0. 0.]


 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D 
NumPy array filled with ones of size `rows x cols`.

In [80]:
import numpy as np

def create_ones_matrix(rows, cols):
    """
    Creates a 2D NumPy array filled with ones.

    Parameters:
        rows (int): Number of rows.
        cols (int): Number of columns.

    Returns:
        numpy.ndarray: 2D array of ones with shape (rows, cols).
    """
    return np.ones((rows, cols))

# Example usage
matrix = create_ones_matrix(3, 4)
print(matrix)



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and 
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified 
`step`.

In [81]:
import numpy as np

def generate_range_array(start, stop, step):
    """
    Creates a NumPy array with values ranging from start to stop (exclusive) with a given step.

    Parameters:
        start (int): Starting value of the sequence.
        stop (int): End value (exclusive).
        step (int): Step size between values.

    Returns:
        numpy.ndarray: Array containing the sequence.
    """
    return np.arange(start, stop, step)

# Example usage
arr = generate_range_array(1, 10, 2)
print(arr)  # Output: [1 3 5 7 9]



[1 3 5 7 9]


 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as 
arguments and generates a NumPy array with num equally spaced values between `start` and `stop` 
(inclusive).

In [14]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage
print(generate_linear_space(0.0, 10.0, 5))


[ 0.   2.5  5.   7.5 10. ]


 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square 
identity matrix of size `n x n` using `numpy.eye`.

In [15]:
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)

# Example usage
print(create_identity_matrix(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 16. Write a function that takes a Python list and converts it into a NumPy array.

In [16]:
import numpy as np

def list_to_numpy_array(lst):
    return np.array(lst)

# Example usage
print(list_to_numpy_array([1, 2, 3, 4, 5]))


[1 2 3 4 5]


 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the 
same data.

In [17]:
import numpy as np

def demonstrate_numpy_view():
    arr = np.array([1, 2, 3, 4, 5])
    arr_view = arr.view()
    return arr, arr_view

# Example usage
original, view_arr = demonstrate_numpy_view()
print("Original array:", original)
print("View of array:", view_arr)


Original array: [1 2 3 4 5]
View of array: [1 2 3 4 5]


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [18]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(arr1, arr2, axis=0))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


19.  Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
 concatenate`.

In [19]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5], [6]])
result = np.concatenate((arr1, arr2), axis=1)
print(result)


[[1 2 5]
 [3 4 6]]


 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

In [20]:
import numpy as np

def vertical_stack(arr_list):
    return np.vstack(arr_list)

# Example usage
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(vertical_stack([arr1, arr2]))


[[1 2 3]
 [4 5 6]]


 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) 
with a given step size.

In [21]:
import numpy as np

def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

# Example usage
print(create_range_array(1, 10, 2))


[1 3 5 7 9]


 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 
(inclusive).

In [22]:
import numpy as np

def generate_equal_space():
    return np.linspace(0, 1, 10)

# Example usage
print(generate_equal_space())


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 
1000 (inclusive).

In [23]:
import numpy as np

def generate_log_space():
    return np.logspace(0, 3, 5)

# Example usage
print(generate_log_space())


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values 
are random integers between 1 and 100.

In [24]:
import numpy as np
import pandas as pd

arr = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(arr, columns=["A", "B", "C"])
print(df)


    A   B   C
0  43  90  37
1   1   9  55
2  98  86  99
3  93  53   9
4  70  18  24


 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column 
with zeros. Use NumPy operations within the Pandas DataFrame.

In [25]:
import numpy as np
import pandas as pd

def replace_negatives(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

# Example usage
data = {'A': [10, -5, 30], 'B': [-3, 20, -8]}
df = pd.DataFrame(data)
print(replace_negatives(df, 'A'))


    A   B
0  10  -3
1   0  20
2  30  -8


 26. Access the 3rd element from the given NumPy array.
 
 arr = np.array([10, 20, 30, 40, 50])

In [26]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[2])  # Index 2 for the 3rd element


30


 27. Retrieve the element at index (1, 2) from the 2D NumPy array.

 arr_2d = np.array([[1, 2, 3],
 

 [4, 5, 6],
 

 [7, 8, 9]])

In [27]:
import numpy as np

arr_2d = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])
print(arr_2d[1, 2])  # Row index 1, Column index 2


6


 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
 
 arr = np.array([3, 8, 2, 10, 5, 7])

In [28]:
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])
print(arr[arr > 5])


[ 8 10  7]


 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
 
 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])  # Slices index 2 to 5


[3 4 5 6]


30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

 arr_2d = np.array([[1, 2, 3],

 [4, 5, 6],

 [7, 8, 9]])

In [30]:
import numpy as np

arr_2d = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print(sub_array)


[[2 3]
 [5 6]]


31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices 
provided in another array.

In [31]:
import numpy as np

def extract_elements(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# Example usage
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])
print(extract_elements(arr, row_indices, col_indices))


[30 50 70]


 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using 
boolean indexing.

In [32]:
import numpy as np

def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

# Example usage
arr = np.array([1, 5, 8, 10, 3])
print(filter_greater_than(arr, 5))


[ 8 10]


 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three 
separate arrays for each dimension.

In [33]:
import numpy as np

def extract_3d_elements(arr, x_idx, y_idx, z_idx):
    return arr[x_idx, y_idx, z_idx]

# Example usage
arr = np.random.randint(1, 100, (3, 3, 3))
x_idx = np.array([0, 1, 2])
y_idx = np.array([1, 2, 0])
z_idx = np.array([2, 1, 0])
print(extract_3d_elements(arr, x_idx, y_idx, z_idx))


[44 80 20]


 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied 
using boolean indexing.

In [34]:
import numpy as np

def filter_two_conditions(arr, cond1, cond2):
    return arr[(arr > cond1) & (arr < cond2)]

# Example usage
arr = np.array([1, 3, 5, 7, 9])
print(filter_two_conditions(arr, 2, 8))


[3 5 7]


 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided 
in separate arrays.

In [35]:
import numpy as np

def extract_using_indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

# Example usage
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
row_indices = np.array([0, 2])
col_indices = np.array([1, 0])
print(extract_using_indices(arr, row_indices, col_indices))


[20 70]


 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [36]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
arr += 5
print(arr)


[[ 6  7  8]
 [ 9 10 11]]


 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the 
corresponding element in arr1 using NumPy broadcasting.

In [37]:
import numpy as np

arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # Shape (3, 4)
result = arr1.T * arr2  # Broadcasting multiplication
print(result)


[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using 
NumPy broadcasting.

In [38]:
import numpy as np

arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)
arr2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90], [100, 110, 120]])  # Shape (4, 3)
result = arr1 + arr2.T  # Broadcasting addition
print(result)


[[ 11  42  73 104]
 [ 21  52  83 114]
 [ 31  62  93 124]]


 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy 
broadcasting.

In [39]:
import numpy as np

arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])  # Shape (1, 3)
result = arr1 + arr2  # Broadcasting addition
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy 
broadcasting. Handle the shape incompatibility.

In [40]:
import numpy as np

arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[1, 2], [3, 4]])  # Shape (2, 2)

try:
    result = arr1 * arr2  # This will cause an error due to shape incompatibility
    print(result)
except ValueError as e:
    print("Shape mismatch error:", e)


Shape mismatch error: operands could not be broadcast together with shapes (2,3) (2,2) 


 41. Calculate column-wise mean for the given array:
 
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [41]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.mean(arr, axis=0))


[2.5 3.5 4.5]


 42. Find maximum value in each row of the given array:
 
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [42]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.max(arr, axis=1))


[3 6]


 43. For the given array, find indices of maximum value in each column.
 
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [43]:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.argmax(arr, axis=0))


[1 1 1]


 44. For the given array, apply custom function to calculate moving sum along rows.
 
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [44]:
import numpy as np

def moving_sum(arr, window=2):
    return np.convolve(arr, np.ones(window, dtype=int), 'valid')

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.apply_along_axis(moving_sum, axis=1, arr=arr)
print(result)


[[ 3  5]
 [ 9 11]]


45. In the given array, check if all elements in each column are even.

 arr = np.array([[2, 4, 6], [3, 5, 7]])

In [45]:
import numpy as np

arr = np.array([[2, 4, 6], [3, 5, 7]])
print(np.all(arr % 2 == 0, axis=0))


[False False False]


46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the 
reshaped matrix.

 original_array = np.array([1, 2, 3, 4, 5, 6])

In [46]:
import numpy as np

def reshape_array(arr, m, n):
    return arr.reshape(m, n)

original_array = np.array([1, 2, 3, 4, 5, 6])
print(reshape_array(original_array, 2, 3))


[[1 2 3]
 [4 5 6]]


 47. Create a function that takes a matrix as input and returns the flattened array.
 
 input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [47]:
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(flatten_matrix(input_matrix))


[1 2 3 4 5 6]


 48. Write a function that concatenates two given arrays along a specified axis.
 
 array1 = np.array([[1, 2], [3, 4]])

 array2 = np.array([[5, 6], [7, 8]])

In [48]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(array1, array2, axis=0))  # Vertical concatenation
print(concatenate_arrays(array1, array2, axis=1))  # Horizontal concatenation


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
 
 original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [49]:
import numpy as np

def split_array(arr, num_splits, axis):
    return np.array_split(arr, num_splits, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(split_array(original_array, 3, axis=0))  # Split along rows


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


 50. Write a function that inserts and then deletes elements from a given array at specified indices.
 
 original_array = np.array([1, 2, 3, 4, 5])

 indices_to_insert = [2, 4]

 values_to_insert = [10, 11]

 indices_to_delete = [1, 3]

In [50]:
import numpy as np

def modify_array(arr, insert_indices, insert_values, delete_indices):
    arr = np.insert(arr, insert_indices, insert_values)
    arr = np.delete(arr, delete_indices)
    return arr

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

print(modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete))


[ 1 10  4 11  5]


 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. 
Perform element-wise addition between `arr1` and `arr2`.

In [51]:
import numpy as np

arr1 = np.random.randint(1, 20, 10)
arr2 = np.arange(1, 11)
print(arr1 + arr2)


[20 20 21 12  9 13 17 27 19 14]


 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers 
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [52]:
import numpy as np

arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
print(arr1 - arr2)


[ 9  7  5  3  1 -1 -3 -5 -7 -9]


 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. 
Perform element-wise multiplication between `arr1` and `arr2`.

In [53]:
import numpy as np

arr1 = np.random.randint(1, 20, 5)
arr2 = np.arange(1, 6)
print(arr1 * arr2)


[ 4 36 57 12 35]


 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 
to 5. Perform element-wise division of `arr1` by `arr2`.

In [54]:
import numpy as np

arr1 = np.arange(2, 11, 2)  # Even numbers from 2 to 10
arr2 = np.arange(1, 6)  # Integers from 1 to 5
print(arr1 / arr2)


[2. 2. 2. 2. 2.]


 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers 
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [55]:
import numpy as np

arr1 = np.arange(1, 6)
arr2 = arr1[::-1]  # Reverse order
print(arr1 ** arr2)


[ 1 16 27 16  5]


 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
 
 arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [56]:
import numpy as np

def count_substring(arr, substring):
    return np.char.count(arr, substring)

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
print(count_substring(arr, 'hello'))


[1 0 1 0 1]


 57. Write a function that extracts uppercase characters from a NumPy array of strings.
 arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
 arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [57]:
import numpy as np

def extract_uppercase(arr):
    return np.array([''.join(filter(str.isupper, s)) for s in arr])

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print(extract_uppercase(arr))


['H' 'W' 'OAI' 'GPT']


58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [58]:
import numpy as np

def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(replace_substring(arr, 'apple', 'orange'))


['orange' 'banana' 'grape' 'pineorange']


 59. Write a function that concatenates strings in a NumPy array element-wise.
 
 arr1 = np.array(['Hello', 'World'])

 arr2 = np.array(['Open', 'AI'])

In [59]:
import numpy as np

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
print(concatenate_strings(arr1, arr2))


['HelloOpen' 'WorldAI']


 60. Write a function that finds the length of the longest string in a NumPy array.
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
 
 arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [60]:
import numpy as np

def longest_string_length(arr):
    return max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(longest_string_length(arr))


9


 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and 
standard deviation of the dataset using NumPy's functions.

In [61]:
import numpy as np

data = np.random.randint(1, 1001, 100)
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Variance:", np.var(data))
print("Standard Deviation:", np.std(data))


Mean: 457.44
Median: 450.0
Variance: 91232.14639999997
Standard Deviation: 302.0465964052566


 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the 
dataset.

In [62]:
import numpy as np

data = np.random.randint(1, 101, 50)
print("25th percentile:", np.percentile(data, 25))
print("75th percentile:", np.percentile(data, 75))


25th percentile: 31.25
75th percentile: 84.5


 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these 
arrays using NumPy's `corrcoef` function.

In [63]:
import numpy as np

arr1 = np.random.randint(1, 101, 50)
arr2 = np.random.randint(1, 101, 50)
print(np.corrcoef(arr1, arr2))


[[1.        0.2245234]
 [0.2245234 1.       ]]


 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [64]:
import numpy as np

mat1 = np.random.randint(1, 10, (3, 2))
mat2 = np.random.randint(1, 10, (2, 3))
print(np.dot(mat1, mat2))


[[64 56 96]
 [64 56 96]
 [47 39 67]]


 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th 
percentiles along with the first and third quartiles.

In [65]:
import numpy as np

data = np.random.randint(10, 1001, 50)
print("10th percentile:", np.percentile(data, 10))
print("50th percentile (median):", np.percentile(data, 50))
print("90th percentile:", np.percentile(data, 90))
print("First quartile (Q1):", np.percentile(data, 25))
print("Third quartile (Q3):", np.percentile(data, 75))


10th percentile: 82.60000000000001
50th percentile (median): 528.0
90th percentile: 875.4000000000001
First quartile (Q1): 215.75
Third quartile (Q3): 691.25


66. Create a NumPy array of integers and find the index of a specific element.

In [66]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
element = 30
print(np.where(arr == element)[0])


[2]


 67. Generate a random NumPy array and sort it in ascending order.

In [67]:
import numpy as np

arr = np.random.randint(1, 101, 10)
print("Original:", arr)
print("Sorted:", np.sort(arr))


Original: [96 37 62 42 81  5 52 64 53 22]
Sorted: [ 5 22 37 42 52 53 62 64 81 96]


 68. Filter elements >20  in the given NumPy array.
 
 arr = np.array([12, 25, 6, 42, 8, 30])

In [68]:
import numpy as np

arr = np.array([12, 25, 6, 42, 8, 30])
print(arr[arr > 20])


[25 42 30]


 69. Filter elements which are divisible by 3 from a given NumPy array.
 
 arr = np.array([1, 5, 8, 12, 15])

In [69]:
import numpy as np

arr = np.array([1, 5, 8, 12, 15])
print(arr[arr % 3 == 0])


[12 15]


70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

 arr = np.array([10, 20, 30, 40, 50])

In [70]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[(arr >= 20) & (arr <= 40)])


[20 30 40]


 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
 arr = np.array([1, 2, 3])

In [82]:
import numpy as np

arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

# Print the byte order
print("Byte Order:", byte_order)



Byte Order: =


72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [72]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print(arr)


[16777216 33554432 50331648]


 73. For the given NumPy array, swap its byte order without modifying the original array using 
`newbyteorder()`.

 arr = np.array([1, 2, 3], dtype=np.int32)

In [86]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Swap the byte order without modifying the original array
swapped_arr = arr.view(arr.dtype.newbyteorder())

# Print original and swapped arrays
print("Original Byte Order:", arr.dtype.byteorder)
print("Swapped Byte Order:", swapped_arr.dtype.byteorder)

# Print arrays to observe changes
print("Original Array:", arr)
print("Swapped Array:", swapped_arr)


Original Byte Order: =
Swapped Byte Order: >
Original Array: [1 2 3]
Swapped Array: [16777216 33554432 50331648]


 74. For the given NumPy array and swap its byte order conditionally based on system endianness using 
`newbyteorder()`.
 arr = np.array([1, 2, 3], dtype=np.int32)

In [87]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Check system endianness
system_endian = np.dtype(int).byteorder
if system_endian == '=':  # '=' means native byte order
    system_endian = '<' if np.little_endian else '>'

# Swap byte order only if it's little-endian (to big-endian) or vice versa
swapped_arr = arr.view(arr.dtype.newbyteorder('S'))  # 'S' means swap

# Print results
print("System Endianness:", system_endian)
print("Original Byte Order:", arr.dtype.byteorder)
print("Swapped Byte Order:", swapped_arr.dtype.byteorder)
print("Original Array:", arr)
print("Swapped Array:", swapped_arr)



System Endianness: <
Original Byte Order: =
Swapped Byte Order: >
Original Array: [1 2 3]
Swapped Array: [16777216 33554432 50331648]


75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` 
attribute `byteorder`.

 arr = np.array([1, 2, 3], dtype=np.int32)

In [88]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)

# Check system's native byte order
system_endian = np.dtype(int).byteorder

# Determine if swapping is needed
if arr.dtype.byteorder in ('=', system_endian):
    print("Byte swapping is NOT necessary.")
else:
    print("Byte swapping is necessary.")


Byte swapping is NOT necessary.


 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify 
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [ ]:
import numpy as np

arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 99

print("Original array:", arr1)
print("Modified copy:", copy_arr)


Original array: [ 1  2  3  4  5  6  7  8  9 10]
Modified copy: [99  2  3  4  5  6  7  8  9 10]


77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from 
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [ ]:
import numpy as np

matrix = np.random.randint(1, 10, (3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 99

print("Original matrix:", matrix)


Original matrix: [[99  3  3]
 [ 7  5  9]
 [ 4  3  4]]


 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice 
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [ ]:
import numpy as np

array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :]
view_b += 5

print("Original array after broadcasting:", array_a)


Original array after broadcasting: [[ 6  7  8]
 [ 9 10 11]
 [ 7  8  9]
 [10 11 12]]


 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view 
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it 
reflects changes in the original `orig_array`.

In [ ]:
import numpy as np

orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 99

print("Original array after modification:", orig_array)


Original array after modification: [[99  2  3  4]
 [ 5  6  7  8]]


 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of 
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`

In [ ]:
import numpy as np

data = np.random.randint(1, 10, (3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 99

print("Original data:", data)
print("Modified copy:", data_copy)


Original data: [[7 3 7 5]
 [7 3 2 1]
 [7 7 4 7]]
Modified copy: [99  7  7  7  7  7]


81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction 
operations between them.

In [ ]:
import numpy as np

A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

print("Addition:\n", A + B)
print("Subtraction:\n", A - B)


Addition:
 [[10 10  2]
 [ 5 12 13]
 [11 10 10]]
Subtraction:
 [[ 4 -4  0]
 [-3 -6 -5]
 [ 1  6  4]]


82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication

In [ ]:
import numpy as np

C = np.random.randint(1, 10, (3, 2))
D = np.random.randint(1, 10, (2, 4))

print("Matrix Multiplication:\n", np.dot(C, D))


Matrix Multiplication:
 [[42 90 78 78]
 [28 60 52 52]
 [16 48 40 28]]


 83. Create a matrix `E` and find its transpose.

In [ ]:
import numpy as np

E = np.random.randint(1, 10, (3, 4))
print("Transpose:\n", E.T)


Transpose:
 [[7 7 9]
 [8 9 3]
 [4 6 6]
 [2 5 8]]


84. Generate a square matrix `F` and compute its determinant

In [ ]:
import numpy as np

F = np.random.randint(1, 10, (3, 3))
print("Determinant:", np.linalg.det(F))


Determinant: 19.000000000000004


 85. Create a square matrix `G` and find its inverse

In [ ]:
import numpy as np

G = np.random.randint(1, 10, (3, 3))
if np.linalg.det(G) != 0:
    print("Inverse:\n", np.linalg.inv(G))
else:
    print("Matrix is singular, no inverse.")


Inverse:
 [[-8. -2.  5.]
 [-5. -2.  4.]
 [11.  3. -7.]]
